title = "fable"
languageCode = "en-gb"
baseURL = "https://fable.sh/"
googleAnalytics = "UA-119532346-1"
tags = ["java", "engineering", "devops", "kubernetes", "terraform", "aws", "cloud"]

[params]
  include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
  latestpostscount       = 5                             # how many posts to display on the home page
  author                 = "Dominic Gunn"
  cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
  dateform               = "Jan 2, 2006"
  dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
  description            = "A place for an engineers ramblings."
  email                  = "dominic@fable.sh"
  faviconfile            = "img/favicon.ico"
  github                 = "//github.com/DominicGunn"
  instagram              = "//instagram.com/anoldguard"
  lang                   = "en"
  linkedin               = "//linkedin.com/in/dominicgunn"
  noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
  selfintro              = "A place for an engineers ramblings."                            # appears in the site header when set to a non-empty string
  twitter                = "//twitter.com/dominic_gunn"
  highlightjs            = true

[permalinks]
  blog  = "blog/:slug/"

## Main Menu
[[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
