version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:

      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout

      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli

      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $HUGO_BUILD_DIR s3://fable.sh --delete
            else
              echo "Not master branch, dry run only"
            fi

      - deploy:
          name: bust cloudfront cache
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
            else
              echo "Not master branch, dry run only"
            fi
